'use client'

import { useEffect, useState } from 'react'
import { SalesShell } from '@/components/sales/SalesShell'
import { MarketingCPLTable } from '@/components/sales/MarketingCPLTable'
import { MarketingROIChart } from '@/components/sales/MarketingROIChart'
import { MarketingFunnel } from '@/components/sales/MarketingFunnel'
import { MarketingExport } from '@/components/sales/MarketingExport'

type MarketingTab = 'cpl' | 'roi' | 'funnel' | 'export'

export default function MarketingPage() {
  const [tab,     setTab]     = useState<MarketingTab>('cpl')
  const [from,    setFrom]    = useState('')
  const [to,      setTo]      = useState('')
  const [apiData, setApiData] = useState<any>(null)
  const [loading, setLoading] = useState(true)

  function load() {
    setLoading(true)
    const sp = new URLSearchParams()
    if (from) sp.set('from', from)
    if (to)   sp.set('to', to)
    fetch(`/api/sales/marketing?${sp}`)
      .then(r => r.json())
      .then(d => { setApiData(d); setLoading(false) })
      .catch(() => setLoading(false))
  }

  useEffect(() => { load() }, []) // eslint-disable-line

  return (
    <SalesShell>
      <div className="page-header" style={{ marginBottom: 24 }}>
        <div className="page-header-left">
          <h1 className="t-page-title">Marketing Analytics</h1>
          <p className="t-caption">Cost per lead, ROI, funnel conversion, and data export</p>
        </div>
        <div className="filter-bar">
          <input className="fadaa-input filter-select" type="date" value={from} onChange={e => setFrom(e.target.value)} style={{ maxWidth: 160 }} aria-label="From" />
          <span className="t-caption">to</span>
          <input className="fadaa-input filter-select" type="date" value={to} onChange={e => setTo(e.target.value)} style={{ maxWidth: 160 }} aria-label="To" />
          <button className="fadaa-btn fadaa-btn-sm" onClick={load}>Apply</button>
          {(from || to) && (
            <button className="fadaa-btn-ghost fadaa-btn-sm" onClick={() => { setFrom(''); setTo(''); setTimeout(load, 0) }}>Clear</button>
          )}
        </div>
      </div>

      {/* Tab bar */}
      <div className="tab-underline-bar" style={{ marginBottom: 24 }}>
        <button className={`tab-underline${tab === 'cpl'    ? ' active' : ''}`} onClick={() => setTab('cpl')}>    CPL Calculator</button>
        <button className={`tab-underline${tab === 'roi'    ? ' active' : ''}`} onClick={() => setTab('roi')}>    ROI Dashboard</button>
        <button className={`tab-underline${tab === 'funnel' ? ' active' : ''}`} onClick={() => setTab('funnel')}> Funnel Report</button>
        <button className={`tab-underline${tab === 'export' ? ' active' : ''}`} onClick={() => setTab('export')}> Data Export</button>
      </div>

      <div style={{ maxWidth: 900 }}>
        {tab === 'cpl' && (
          <div className="fadaa-card" style={{ padding: '20px 24px' }}>
            <div className="card-header" style={{ marginBottom: 20 }}>
              <div>
                <h3 className="t-section-title">CPL Calculator</h3>
                <p className="t-caption" style={{ marginTop: 3 }}>Enter ad spend per source per month to compute cost-per-lead and conversion KPIs.</p>
              </div>
            </div>
            <MarketingCPLTable from={from} to={to} />
          </div>
        )}

        {tab === 'roi' && (
          <div className="fadaa-card" style={{ padding: '20px 24px' }}>
            <div className="card-header" style={{ marginBottom: 20 }}>
              <div>
                <h3 className="t-section-title">ROI Dashboard</h3>
                <p className="t-caption" style={{ marginTop: 3 }}>Spend vs revenue generated by source.</p>
              </div>
            </div>
            {loading
              ? <div className="skeleton" style={{ height: 260, borderRadius: 8 }} />
              : <MarketingROIChart data={apiData?.kpis ?? []} />
            }
          </div>
        )}

        {tab === 'funnel' && (
          <div className="fadaa-card" style={{ padding: '20px 24px' }}>
            <div className="card-header" style={{ marginBottom: 20 }}>
              <div>
                <h3 className="t-section-title">Funnel Conversion Report</h3>
                <p className="t-caption" style={{ marginTop: 3 }}>Overall pipeline conversion rates from lead to won.</p>
              </div>
              <button onClick={() => window.print()} className="fadaa-btn fadaa-btn-sm">↓ PDF</button>
            </div>
            {loading
              ? <div className="skeleton" style={{ height: 300, borderRadius: 8 }} />
              : <MarketingFunnel data={apiData?.funnel ?? null} />
            }
          </div>
        )}

        {tab === 'export' && (
          <div className="fadaa-card" style={{ padding: '20px 24px' }}>
            <div className="card-header" style={{ marginBottom: 20 }}>
              <div>
                <h3 className="t-section-title">Smart Data Export</h3>
                <p className="t-caption" style={{ marginTop: 3 }}>Download filtered lead data as CSV.</p>
              </div>
            </div>
            <MarketingExport />
          </div>
        )}
      </div>
    </SalesShell>
  )
}
